"""Auto relação na tabela dio_porta

Revision ID: 2a074e255c77
Revises: 62bcf8ac9a08
Create Date: 2019-02-25 17:35:09.961798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a074e255c77'
down_revision = '62bcf8ac9a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dio_porta', sa.Column('bypass', sa.Boolean(), nullable=False))
    op.add_column('dio_porta', sa.Column('porta_destino_id', sa.Integer(), nullable=True))
    op.drop_constraint('dio_porta_local_destino_id_fkey', 'dio_porta', type_='foreignkey')
    op.create_foreign_key(None, 'dio_porta', 'dio_porta', ['porta_destino_id'], ['id'])
    op.drop_column('dio_porta', 'local_destino_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dio_porta', sa.Column('local_destino_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dio_porta', type_='foreignkey')
    op.create_foreign_key('dio_porta_local_destino_id_fkey', 'dio_porta', 'local', ['local_destino_id'], ['id'])
    op.drop_column('dio_porta', 'porta_destino_id')
    op.drop_column('dio_porta', 'bypass')
    # ### end Alembic commands ###
