"""Banco completo

Revision ID: 81614787bc72
Revises: 
Create Date: 2019-03-14 15:29:55.702440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81614787bc72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabo_fibra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('quantidade_fibras', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_cabo_fibra_nome'), 'cabo_fibra', ['nome'], unique=True, schema='dev')
    op.create_table('estado_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='dev'
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_local_nome'), 'local', ['nome'], unique=True, schema='dev')
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True, schema='dev')
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_user_username'), 'user', ['username'], unique=True, schema='dev')
    op.create_table('dio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['dev.local.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_table('dio_porta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porta_destino_id', sa.Integer(), nullable=True),
    sa.Column('dio_id', sa.Integer(), nullable=False),
    sa.Column('numero_porta', sa.Integer(), nullable=False),
    sa.Column('estado_link_id', sa.Integer(), nullable=True),
    sa.Column('fibra_cabo_id', sa.Integer(), nullable=True),
    sa.Column('fibra_numero', sa.Integer(), nullable=True),
    sa.Column('switch_porta', sa.String(length=128), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('porta_bypass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dio_id'], ['dev.dio.id'], ),
    sa.ForeignKeyConstraint(['estado_link_id'], ['dev.estado_link.id'], ),
    sa.ForeignKeyConstraint(['fibra_cabo_id'], ['dev.cabo_fibra.id'], ),
    sa.ForeignKeyConstraint(['porta_bypass_id'], ['dev.dio_porta.id'], ),
    sa.ForeignKeyConstraint(['porta_destino_id'], ['dev.dio_porta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dio_porta', schema='dev')
    op.drop_table('dio', schema='dev')
    op.drop_index(op.f('ix_dev_user_username'), table_name='user', schema='dev')
    op.drop_table('user', schema='dev')
    op.drop_index(op.f('ix_dev_revoked_tokens_jti'), table_name='revoked_tokens', schema='dev')
    op.drop_table('revoked_tokens', schema='dev')
    op.drop_index(op.f('ix_dev_local_nome'), table_name='local', schema='dev')
    op.drop_table('local', schema='dev')
    op.drop_table('estado_link', schema='dev')
    op.drop_index(op.f('ix_dev_cabo_fibra_nome'), table_name='cabo_fibra', schema='dev')
    op.drop_table('cabo_fibra', schema='dev')
    # ### end Alembic commands ###
