"""Porta de bypass

Revision ID: e2096e2b9d66
Revises: 2a074e255c77
Create Date: 2019-02-25 17:44:54.859207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2096e2b9d66'
down_revision = '2a074e255c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dio_porta', sa.Column('local_destino_id', sa.Integer(), nullable=False))
    op.add_column('dio_porta', sa.Column('porta_bypass_id', sa.Integer(), nullable=True))
    op.alter_column('dio_porta', 'numero_porta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dio_porta', 'observacao',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'dio_porta', 'local', ['local_destino_id'], ['id'])
    op.create_foreign_key(None, 'dio_porta', 'dio_porta', ['porta_bypass_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dio_porta', type_='foreignkey')
    op.drop_constraint(None, 'dio_porta', type_='foreignkey')
    op.alter_column('dio_porta', 'observacao',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dio_porta', 'numero_porta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dio_porta', 'porta_bypass_id')
    op.drop_column('dio_porta', 'local_destino_id')
    # ### end Alembic commands ###
