"""Primeira versao

Revision ID: 62bcf8ac9a08
Revises: 
Create Date: 2019-02-25 16:40:27.936280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bcf8ac9a08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabo_fibra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('quantidade_fibras', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('numero_portas', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dio_porta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.Column('local_destino_id', sa.Integer(), nullable=True),
    sa.Column('dio_id', sa.Integer(), nullable=False),
    sa.Column('numero_porta', sa.Integer(), nullable=True),
    sa.Column('estado_link_id', sa.Integer(), nullable=True),
    sa.Column('fibra_cabo_id', sa.Integer(), nullable=True),
    sa.Column('fibra_grupo', sa.Integer(), nullable=True),
    sa.Column('fibra_numero', sa.Integer(), nullable=True),
    sa.Column('switch_porta', sa.String(length=128), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dio_id'], ['dio.id'], ),
    sa.ForeignKeyConstraint(['estado_link_id'], ['estado_link.id'], ),
    sa.ForeignKeyConstraint(['fibra_cabo_id'], ['cabo_fibra.id'], ),
    sa.ForeignKeyConstraint(['last_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['local_destino_id'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dio_porta')
    op.drop_table('dio')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('local')
    op.drop_table('estado_link')
    op.drop_table('cabo_fibra')
    # ### end Alembic commands ###
