"""nullable dio observacao

Revision ID: a4c9c0701b07
Revises: 192332b9b14f
Create Date: 2019-03-07 17:50:44.672805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c9c0701b07'
down_revision = '192332b9b14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dio', 'observacao',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dio', 'observacao',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
